---
M.d.: M.D.
M.s: M.S
-s: -S
.t.: .T.
.c.: .C.
-m: -M
-h: -H
-w: -W
.y.: .Y.
-k: -K
MD: M.D.
n-c: n-C
t-f: t-F
e-j: e-J
g-l: g-L
Mcdaniel: McDaniel
Mcswain: McSwain
K.l.: K.L.
y-c: y-C
u-l: u-L
t-r: t-R
Mcknight: McKnight
g-c: g-C
n-y: n-Y
i-w: i-W
s-d: s-D
i-c: i-C
Mcdonnell: McDonnell
Uc-uc: Uc-Uc
Macgowan: MacGowan
o-g: o-G
m-v: m-V
k-t: k-T
m-u: m-U
o-r: o-R